language: node_js
sudo: false
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - npm install -g gulp
after_success:
  - gulp ci
addons:
  code_climate:
    repo_token: 6ae42073fcd899c76d55ed13884f6c9688bfe2a13c9e4b57a0cb425dce8ff7c1
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: BEsF1lt1brlCU34+sjBxqWk/9TL7BKF/7m7LFUPZgsTBFwqo4eNpscNysN8iuRazNheY2ny+Q2HFX9oMVa8EK/xv7YYj6h7eRZdflUmZfdn4jRC5iTJ9JGJ8jG1SE2VEJ3JvY2iaf6s/ci69pHcWU04v1GNzuM0jZ93tVX6Vwl4=
  on:
    tags: true
    all_branches: true
