language: node_js
sudo: false
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - npm install -g gulp
after_success:
  - gulp ci
addons:
  code_climate:
    repo_token: 
      secure: C+Z9Y4ZGAwmc10zfQSgzjYkaWXs8aztaVTwSyJIe/YJupzCzjKNwXwb1e0fj8yr0MsZNdnAqclNV8dcGe7Oo2unvmCW2EJ2GOpzbE8bVlUmSa+QxgBX32KXj2L12atZHGIU2Idw0itmSGA2yuqcPKVQYJTc0an7DqcxBE3qiPjc=
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: BEsF1lt1brlCU34+sjBxqWk/9TL7BKF/7m7LFUPZgsTBFwqo4eNpscNysN8iuRazNheY2ny+Q2HFX9oMVa8EK/xv7YYj6h7eRZdflUmZfdn4jRC5iTJ9JGJ8jG1SE2VEJ3JvY2iaf6s/ci69pHcWU04v1GNzuM0jZ93tVX6Vwl4=
  on:
    tags: true
    all_branches: true
