language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
after_success:
- istanbul cover ./node_modules/mocha/bin/_mocha test/*tests.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: BEsF1lt1brlCU34+sjBxqWk/9TL7BKF/7m7LFUPZgsTBFwqo4eNpscNysN8iuRazNheY2ny+Q2HFX9oMVa8EK/xv7YYj6h7eRZdflUmZfdn4jRC5iTJ9JGJ8jG1SE2VEJ3JvY2iaf6s/ci69pHcWU04v1GNzuM0jZ93tVX6Vwl4=
  on:
    tags: true
    branch: master
